{% set name = "Flask-Migrate" %}
{% set version = "2.5.3" %}
{% set bundle = "tar.gz" %}
{% set hash = "a69d508c2e09d289f6e55a417b3b8c7bfe70e640f53d2d9deb0d056a384f37ee" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  preserve_egg_dir: true
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - flask >=0.9
    - flask-sqlalchemy >=1.0
    - alembic >=0.6

test:
  imports:
    - flask_migrate

about:
  home: https://github.com/miguelgrinberg/flask-migrate/
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: SQLAlchemy database migrations for Flask applications using Alembic
  dev_url: https://github.com/miguelgrinberg/flask-migrate/
  doc_url: https://flask-migrate.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
