appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: vCpidFkebvK61ppvEuguO9gv/5tONGTMsNWtoQ8ekIccUm+D8G/7XZ7pBaj4ov6S9Qr0/Bt1z7nhJ2gDIY0hB5/tJOO6oqlLMmwW237KQ+1tryMbWtKgOyqmAZVU/MC60lxOtGIAufUafYaDNIN7yMDr/192014X26AKRuBMeTlB4H6sROlFpgl6Exv7EnY0U50IYe81F6Bka02Wt0lKn0QW6rJgN+IdBhG7tkO7F19DhSVC0DD8D92x2NPtMAa6Pp59HCAHZ/1UUb16H968qNu2GMa+Vl4XfiO+x4BeOtfzLzdK03YbOqgL5tdUNLhbwS6wyMImkp5PBcv2mPIpwvGiLV+bHh1CGblc8c0ExdEK/lLQoJASSuBakxJNMd+eVSGJgK1SJYRvGqglvuVksec2/JHUXBEaA/NLeDOjEParFsTlDn0EzZK21VO20e6/as/d+0hc4XBuUKTxmeIHttmZ3+uodqhjKjuBvTG4KrLcTMYyOJG2UP/wJKQN9092Xq+siO8DNMqn7v+Usf7tKSRFJzyJfkzJwF4TBHYvGIuU8iilpjFHja38if+Y4cOgvb1VyeU/JU7GBeG0aKNz9SxhA1OX9Tzf1kGsbbfiBrWk1EEBFm80QsJmsOJRpm/R0Fu1J4pkrgSnEW/exlZhmmNR+nvaDQWTcuzieb4fQFA=}
